version: '3'

services:

  app:
    build: .
    container_name: golang_app
    volumes:
      - ./src:/go/src/app
      - sock-db:/run/mysqld
    environment:
      - VIRTUAL_HOST=localhost
    logging:
      options:
        max-size: 100m
    restart: always

  db:
    image: mysql:5.6
    container_name: golang_db
    volumes:
      - db:/var/lib/mysql
      - sock-db:/run/mysqld
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    logging:
      options:
        max-size: 100m
    restart: always

volumes:
  db:
  sock-db:
